# Generated by Django 4.0.4 on 2023-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_banner_alter_faq_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='title_first_word',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title_second_word',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
