# Generated by Django 4.0.4 on 2023-02-07 06:43

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_banner_title_banner_title_first_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=129)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='portfolio/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
