# Generated by Django 4.0.4 on 2023-02-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO About',
            },
        ),
        migrations.CreateModel(
            name='SeoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Blog',
            },
        ),
        migrations.CreateModel(
            name='SeoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Contact',
            },
        ),
        migrations.CreateModel(
            name='SeoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Home',
            },
        ),
        migrations.CreateModel(
            name='SeoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Portfolio',
            },
        ),
        migrations.CreateModel(
            name='SeoServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Services',
            },
        ),
    ]
