# Generated by Django 4.0.4 on 2023-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_seoabout_seoblog_seocontact_seohome_seoportfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoACServiceAndRepairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO AC Service and Repairs',
            },
        ),
        migrations.CreateModel(
            name='SeoBuildingCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Building Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoCarpentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Carpentry',
            },
        ),
        migrations.CreateModel(
            name='SeoCarpetCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Carpet Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoConstructionCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Construction Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoElectricals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Electricals',
            },
        ),
        migrations.CreateModel(
            name='SeoGeneralMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO General Maintenance',
            },
        ),
        migrations.CreateModel(
            name='SeoMasonry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Masonry',
            },
        ),
        migrations.CreateModel(
            name='SeoMattressCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Mattress Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoOfficeCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Office Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Painting',
            },
        ),
        migrations.CreateModel(
            name='SeoPlumbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Plumbing',
            },
        ),
        migrations.CreateModel(
            name='SeoResidentialCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Residential Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoSofaCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Sofa Cleaning',
            },
        ),
        migrations.CreateModel(
            name='SeoTiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Tiling',
            },
        ),
        migrations.CreateModel(
            name='SeoWallpaperFixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO Wallpaper Fixing',
            },
        ),
    ]
